using System.Collections.Generic;
using UnityEngine;
using CivilizationEvolution.Core;
using CivilizationEvolution.Economy;
using CivilizationEvolution.Politics;
using CivilizationEvolution.Race;
using CivilizationEvolution.Tech;
using CivilizationEvolution.Thought;

namespace CivilizationEvolution.Role
{
    public static class PersonalityTraitDatabase
    {
                public static readonly PersonalityTrait[] All =
        {
            // ===== 勇气 brave（L1勇气/大胆 · L2勇敢 · L3无畏）=====
            new PersonalityTrait { traitId="brave_1", traitName="勇气", description="大胆——当周围大多数人退缩时，却愿意迎难而上的意志",
                category=TraitCategory.Personality, martialMod=1f, warfareMod=1f,
                conflictingTraits=new List<string>{"craven_1","craven_2","craven_3"} },
            new PersonalityTrait { traitId="brave_2", traitName="勇敢", description="大胆——勇气是宫闱轶事中不可或缺的；战斗以其名字被铭记",
                category=TraitCategory.Personality, martialMod=2f, warfareMod=2f,
                conflictingTraits=new List<string>{"craven_1","craven_2","craven_3"},
                requiredTraits=new List<string>{"brave_1"} },
            new PersonalityTrait { traitId="brave_3", traitName="无畏", description="大胆——迎战险境，如同他人追求爱人一般；战场上罕有人能望其项背",
                category=TraitCategory.Personality, martialMod=3f, warfareMod=3f,
                conflictingTraits=new List<string>{"craven_1","craven_2","craven_3"},
                requiredTraits=new List<string>{"brave_2"} },
            // ===== 慎重 craven（L1慎重/小心 · L2谨慎 · L3怯懦）=====
            new PersonalityTrait { traitId="craven_1", traitName="慎重", description="小心——对风险、危险与对抗的回避，在压力下呼声愈高",
                category=TraitCategory.Personality, martialMod=-1f, intrigueMod=1f,
                conflictingTraits=new List<string>{"brave_1","brave_2","brave_3"} },
            new PersonalityTrait { traitId="craven_2", traitName="谨慎", description="小心——慎重是出了名的；战事都安排给别人去统领",
                category=TraitCategory.Personality, martialMod=-2f, intrigueMod=2f,
                conflictingTraits=new List<string>{"brave_1","brave_2","brave_3"},
                requiredTraits=new List<string>{"craven_1"} },
            new PersonalityTrait { traitId="craven_3", traitName="怯懦", description="小心——无论如何都不肯冒险；领地因此蒙受了无数种隐而未显的损失",
                category=TraitCategory.Personality, martialMod=-3f, intrigueMod=3f,
                conflictingTraits=new List<string>{"brave_1","brave_2","brave_3"},
                requiredTraits=new List<string>{"craven_2"} },
            // ===== 同情心 compassionate（L1同情心/善良 · L2慈悲 · L3圣母般）=====
            new PersonalityTrait { traitId="compassionate_1", traitName="同情心", description="善良——向有需要之人伸出援手，不计回报",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f,
                conflictingTraits=new List<string>{"callous_1","callous_2","callous_3"} },
            new PersonalityTrait { traitId="compassionate_2", traitName="慈悲", description="善良——仁慈成了此地景象；灾荒年月，郡中穷苦人上门求助",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f,
                conflictingTraits=new List<string>{"callous_1","callous_2","callous_3"},
                requiredTraits=new List<string>{"compassionate_1"} },
            new PersonalityTrait { traitId="compassionate_3", traitName="圣母般", description="善良——施予之多，已超出府中所能承受；大门向所有来者敞开",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f,
                conflictingTraits=new List<string>{"callous_1","callous_2","callous_3"},
                requiredTraits=new List<string>{"compassionate_2"} },
            // ===== 冷漠 callous（L1冷漠/疏离 · L2无情 · L3铁石心肠）=====
            new PersonalityTrait { traitId="callous_1", traitName="冷漠", description="疏离——对不直接关系到自己的痛苦十分冷淡",
                category=TraitCategory.Personality, intrigueMod=1f, martialMod=1f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"} },
            new PersonalityTrait { traitId="callous_2", traitName="无情", description="疏离——漠然在每次觐见中都明明白白；泪水无法打动他们",
                category=TraitCategory.Personality, intrigueMod=2f, martialMod=2f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"},
                requiredTraits=new List<string>{"callous_1"} },
            new PersonalityTrait { traitId="callous_3", traitName="铁石心肠", description="疏离——已全然不再假装置身于仁慈；死刑令的签署也懒得多看一眼名字",
                category=TraitCategory.Personality, intrigueMod=3f, martialMod=3f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"},
                requiredTraits=new List<string>{"callous_2"} },
            // ===== 贪念 greedy（L1贪念/精打细算 · L2贪婪 · L3贪得无厌）=====
            new PersonalityTrait { traitId="greedy_1", traitName="贪念", description="精打细算——对钱币与财物的抓攫，随着每笔交易愈发沉重",
                category=TraitCategory.Personality, stewardshipMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"generous_1","generous_2","generous_3"} },
            new PersonalityTrait { traitId="greedy_2", traitName="贪婪", description="精打细算——对财富的追逐形塑着每次觐见；礼物在收下之前先被称量",
                category=TraitCategory.Personality, stewardshipMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"generous_1","generous_2","generous_3"},
                requiredTraits=new List<string>{"greedy_1"} },
            new PersonalityTrait { traitId="greedy_3", traitName="贪得无厌", description="精打细算——已将国库榨干却浑然不觉；友谊本身也成了一桩交易",
                category=TraitCategory.Personality, stewardshipMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"generous_1","generous_2","generous_3"},
                requiredTraits=new List<string>{"greedy_2"} },
            // ===== 慷慨 generous（L1慷慨/乐善 · L2好施 · L3博施）=====
            new PersonalityTrait { traitId="generous_1", traitName="慷慨", description="乐善——对黄金、礼物与恩惠的洒脱之手，以及不求回报施予",
                category=TraitCategory.Personality, diplomacyMod=1f, stewardshipMod=-1f,
                conflictingTraits=new List<string>{"greedy_1","greedy_2","greedy_3"} },
            new PersonalityTrait { traitId="generous_2", traitName="好施", description="乐善——赈济在本地教堂里被称颂；上门的请愿者们很少空手而归",
                category=TraitCategory.Personality, diplomacyMod=2f, stewardshipMod=-2f,
                conflictingTraits=new List<string>{"greedy_1","greedy_2","greedy_3"},
                requiredTraits=new List<string>{"generous_1"} },
            new PersonalityTrait { traitId="generous_3", traitName="博施", description="乐善——不顾一切劝诫，施予无度；国库是拿来尊荣旁人的手段",
                category=TraitCategory.Personality, diplomacyMod=3f, stewardshipMod=-3f,
                conflictingTraits=new List<string>{"greedy_1","greedy_2","greedy_3"},
                requiredTraits=new List<string>{"generous_2"} },
            // ===== 诚信 honest（L1诚信/直率 · L2诚实 · L3坦率无隐）=====
            new PersonalityTrait { traitId="honest_1", traitName="诚信", description="直率——拒绝粉饰真相，即使礼节或自身利益要求如此",
                category=TraitCategory.Personality, diplomacyMod=1f, intrigueMod=-1f,
                conflictingTraits=new List<string>{"deceitful_1","deceitful_2","deceitful_3"} },
            new PersonalityTrait { traitId="honest_2", traitName="诚实", description="直率——以诚实的品格在宫廷中著称；对手们畏惧他那些毫不留情的质问",
                category=TraitCategory.Personality, diplomacyMod=2f, intrigueMod=-2f,
                conflictingTraits=new List<string>{"deceitful_1","deceitful_2","deceitful_3"},
                requiredTraits=new List<string>{"honest_1"} },
            new PersonalityTrait { traitId="honest_3", traitName="坦率无隐", description="直率——即使出于体面，也无法掩饰其坦率；君王们曾被当面指出过自己的过失",
                category=TraitCategory.Personality, diplomacyMod=3f, intrigueMod=-3f,
                conflictingTraits=new List<string>{"deceitful_1","deceitful_2","deceitful_3"},
                requiredTraits=new List<string>{"honest_2"} },
            // ===== 狡诈 deceitful（L1狡诈/机灵 · L2狡猾 · L3背信弃义）=====
            new PersonalityTrait { traitId="deceitful_1", traitName="狡诈", description="机灵——对谎言、半真半假的话和恰到好处的沉默驾轻就熟",
                category=TraitCategory.Personality, intrigueMod=2f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"honest_1","honest_2","honest_3"} },
            new PersonalityTrait { traitId="deceitful_2", traitName="狡猾", description="机灵——诡计多端的名声并非空穴来风；协议必被细读，誓言也需证人衡量",
                category=TraitCategory.Personality, intrigueMod=3f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"honest_1","honest_2","honest_3"},
                requiredTraits=new List<string>{"deceitful_1"} },
            new PersonalityTrait { traitId="deceitful_3", traitName="背信弃义", description="机灵——既不能托付密封的信件，也不能指望他信守承诺；每句话都像棋盘上的一步棋",
                category=TraitCategory.Personality, intrigueMod=4f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"honest_1","honest_2","honest_3"},
                requiredTraits=new List<string>{"deceitful_2"} },
            // ===== 平和 calm（L1平和/从容 · L2冷静 · L3心如止水）=====
            new PersonalityTrait { traitId="calm_1", traitName="平和", description="从容——一种沉稳的性情，即使面对挑衅也能保持泰然自若",
                category=TraitCategory.Personality, learningMod=1f, intrigueMod=1f,
                conflictingTraits=new List<string>{"wrathful_1","wrathful_2","wrathful_3"} },
            new PersonalityTrait { traitId="calm_2", traitName="冷静", description="从容——沉着是御前会议的定海神针；是房间里紧张气氛的逐渐降温",
                category=TraitCategory.Personality, learningMod=2f, intrigueMod=2f,
                conflictingTraits=new List<string>{"wrathful_1","wrathful_2","wrathful_3"},
                requiredTraits=new List<string>{"calm_1"} },
            new PersonalityTrait { traitId="calm_3", traitName="心如止水", description="从容——面对足以击垮他人的消息仍岿然不动；战祸、瘟疫与背叛递到同一张平静的面孔前",
                category=TraitCategory.Personality, learningMod=3f, intrigueMod=3f,
                conflictingTraits=new List<string>{"wrathful_1","wrathful_2","wrathful_3"},
                requiredTraits=new List<string>{"calm_2"} },
            // ===== 怒火 wrathful（L1怒火/性急 · L2易怒 · L3狂怒）=====
            new PersonalityTrait { traitId="wrathful_1", traitName="怒火", description="性急——一腔过于易燃又冷却太慢的脾气，在宫廷日常事务上留下焦痕",
                category=TraitCategory.Personality, martialMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"calm_1","calm_2","calm_3"} },
            new PersonalityTrait { traitId="wrathful_2", traitName="易怒", description="性急——怒气在廷中无人不知；仆从们步步小心，所受的轻蔑也鲜少被遗忘",
                category=TraitCategory.Personality, martialMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"calm_1","calm_2","calm_3"},
                requiredTraits=new List<string>{"wrathful_1"} },
            new PersonalityTrait { traitId="wrathful_3", traitName="狂怒", description="性急——暴怒已是低声相传的传奇；就连忠勇之士也学会了辨识风暴前的沉寂",
                category=TraitCategory.Personality, martialMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"calm_1","calm_2","calm_3"},
                requiredTraits=new List<string>{"wrathful_2"} },
            // ===== 热枕 zealous（L1热枕/虔诚 · L2狂热 · L3盲信）=====
            new PersonalityTrait { traitId="zealous_1", traitName="热枕", description="虔诚——对信仰怀有炽烈的确信，不容妥协，也几乎不能容忍怀疑",
                category=TraitCategory.Personality, learningMod=1f, warfareMod=1f,
                conflictingTraits=new List<string>{"cynical_1","cynical_2","cynical_3"} },
            new PersonalityTrait { traitId="zealous_2", traitName="狂热", description="虔诚——虔诚是整个家府的界碑；每逢瞻礼教堂必满，谈话也常绕回教义",
                category=TraitCategory.Personality, learningMod=2f, warfareMod=2f,
                conflictingTraits=new List<string>{"cynical_1","cynical_2","cynical_3"},
                requiredTraits=new List<string>{"zealous_1"} },
            new PersonalityTrait { traitId="zealous_3", traitName="盲信", description="虔诚——信仰炽烈，不容半分妥协；异端绝不容忍，即便是多年盟友也要按教义问答衡量",
                category=TraitCategory.Personality, learningMod=3f, warfareMod=3f,
                conflictingTraits=new List<string>{"cynical_1","cynical_2","cynical_3"},
                requiredTraits=new List<string>{"zealous_2"} },
            // ===== 犬儒主义 cynical（L1犬儒主义/不轻信 · L2愤世嫉俗 · L3虚无）=====
            new PersonalityTrait { traitId="cynical_1", traitName="犬儒主义", description="不轻信——对崇高目的抱有怀疑，并私下把每一种动机都解读为更卑劣的东西",
                category=TraitCategory.Personality, intrigueMod=1f, learningMod=-1f,
                conflictingTraits=new List<string>{"zealous_1","zealous_2","zealous_3"} },
            new PersonalityTrait { traitId="cynical_2", traitName="愤世嫉俗", description="不轻信——怀疑态度早已为人所知；神职人员害怕他的提问，誓言换来的只是淡淡一笑",
                category=TraitCategory.Personality, intrigueMod=2f, learningMod=-2f,
                conflictingTraits=new List<string>{"zealous_1","zealous_2","zealous_3"},
                requiredTraits=new List<string>{"cynical_1"} },
            new PersonalityTrait { traitId="cynical_3", traitName="虚无", description="不轻信——看不到欲望与私利之外的任何目的；信仰仪式也像忍受四季更替一样耐着性子遵守",
                category=TraitCategory.Personality, intrigueMod=3f, learningMod=-3f,
                conflictingTraits=new List<string>{"zealous_1","zealous_2","zealous_3"},
                requiredTraits=new List<string>{"cynical_2"} },
            // ===== 野心 ambitious（L1野心/渴望上进 · L2野心勃勃 · L3利欲熏心）=====
            new PersonalityTrait { traitId="ambitious_1", traitName="野心", description="渴望上进——一种不甘于现状，渴望更高职位、头衔或声望的追求",
                category=TraitCategory.Personality, warfareMod=1f, diplomacyMod=1f, stewardshipMod=-1f,
                conflictingTraits=new List<string>{"content_1","content_2","content_3"} },
            new PersonalityTrait { traitId="ambitious_2", traitName="野心勃勃", description="渴望上进——野心明眼人都看得出来；权衡联盟时看重影响范围，安排婚姻时看重机会",
                category=TraitCategory.Personality, warfareMod=2f, diplomacyMod=2f, stewardshipMod=-2f,
                conflictingTraits=new List<string>{"content_1","content_2","content_3"},
                requiredTraits=new List<string>{"ambitious_1"} },
            new PersonalityTrait { traitId="ambitious_3", traitName="利欲熏心", description="渴望上进——全然受晋身高位之念所役使；每一场筵席、征战、恩惠皆被用作向上攀爬的阶梯",
                category=TraitCategory.Personality, warfareMod=3f, diplomacyMod=3f, stewardshipMod=-3f,
                conflictingTraits=new List<string>{"content_1","content_2","content_3"},
                requiredTraits=new List<string>{"ambitious_2"} },
            // ===== 满足感 content（L1满足感/满意 · L2知足 · L3安于现状）=====
            new PersonalityTrait { traitId="content_1", traitName="满足感", description="满意——安然承受自身的命数，不再向门第或命运索取已被赐予之外的东西",
                category=TraitCategory.Personality, stewardshipMod=1f, diplomacyMod=1f, warfareMod=-1f,
                conflictingTraits=new List<string>{"ambitious_1","ambitious_2","ambitious_3"} },
            new PersonalityTrait { traitId="content_2", traitName="知足", description="满意——知足之名远近皆知；凡有晋身之邀皆谢而辞之；账册所计不过来岁收支",
                category=TraitCategory.Personality, stewardshipMod=2f, diplomacyMod=2f, warfareMod=-2f,
                conflictingTraits=new List<string>{"ambitious_1","ambitious_2","ambitious_3"},
                requiredTraits=new List<string>{"content_1"} },
            new PersonalityTrait { traitId="content_3", traitName="安于现状", description="满意——任凭何等诱引，亦不能使其动念求荣；帝国在其周遭兴亡更替，心神仍安放于旧日炉火之前",
                category=TraitCategory.Personality, stewardshipMod=3f, diplomacyMod=3f, warfareMod=-3f,
                conflictingTraits=new List<string>{"ambitious_1","ambitious_2","ambitious_3"},
                requiredTraits=new List<string>{"content_2"} },
            // ===== 勤勉 diligent（L1勤勉/尽责 · L2勤恳 · L3宵衣旰食）=====
            new PersonalityTrait { traitId="diligent_1", traitName="勤勉", description="尽责——不论心境与阴晴，对工作恒久不懈的投入",
                category=TraitCategory.Personality, stewardshipMod=1f, learningMod=1f,
                conflictingTraits=new List<string>{"lazy_1","lazy_2","lazy_3"} },
            new PersonalityTrait { traitId="diligent_2", traitName="勤恳", description="尽责——勤恳是宫廷的动力；无一事被遗忘，无一份请愿不被答复",
                category=TraitCategory.Personality, stewardshipMod=2f, learningMod=2f,
                conflictingTraits=new List<string>{"lazy_1","lazy_2","lazy_3"},
                requiredTraits=new List<string>{"diligent_1"} },
            new PersonalityTrait { traitId="diligent_3", traitName="宵衣旰食", description="尽责——每夜劳作到超出所有合理时刻，劝也劝不住；城堡其余角落早已沉寂，房厅灯火依旧亮着",
                category=TraitCategory.Personality, stewardshipMod=3f, learningMod=3f,
                conflictingTraits=new List<string>{"lazy_1","lazy_2","lazy_3"},
                requiredTraits=new List<string>{"diligent_2"} },
            // ===== 惰性 lazy（L1惰性/闲散 · L2懒惰 · L3怠惰成性）=====
            new PersonalityTrait { traitId="lazy_1", traitName="惰性", description="闲散——当他人之手可代劳时，自己便不愿起身、决断或劳作",
                category=TraitCategory.Personality, stewardshipMod=-1f, learningMod=-1f, intrigueMod=1f,
                conflictingTraits=new List<string>{"diligent_1","diligent_2","diligent_3"} },
            new PersonalityTrait { traitId="lazy_2", traitName="懒惰", description="闲散——厌劳人尽皆知；臣属们学会了将决议拟好大半再呈上",
                category=TraitCategory.Personality, stewardshipMod=-2f, learningMod=-2f, intrigueMod=2f,
                conflictingTraits=new List<string>{"diligent_1","diligent_2","diligent_3"},
                requiredTraits=new List<string>{"lazy_1"} },
            new PersonalityTrait { traitId="lazy_3", traitName="怠惰成性", description="闲散——已数月未签一纸谕令；信使候在门口，案头积满了灰，封地全赖旁人勉力维系",
                category=TraitCategory.Personality, stewardshipMod=-3f, learningMod=-3f, intrigueMod=3f,
                conflictingTraits=new List<string>{"diligent_1","diligent_2","diligent_3"},
                requiredTraits=new List<string>{"lazy_2"} },
            // ===== 耐性 patient（L1耐性/宽忍 · L2耐心 · L3坚忍）=====
            new PersonalityTrait { traitId="patient_1", traitName="耐性", description="宽忍——情愿等待、忍耐，让事态顺其自身的节奏展开",
                category=TraitCategory.Personality, learningMod=1f, diplomacyMod=1f, martialMod=-1f,
                conflictingTraits=new List<string>{"impatient_1","impatient_2","impatient_3"} },
            new PersonalityTrait { traitId="patient_2", traitName="耐心", description="宽忍——耐心是治理的工具；指望速速作答的对手，往往被审慎节奏弄得狼狈不堪",
                category=TraitCategory.Personality, learningMod=2f, diplomacyMod=2f, martialMod=-2f,
                conflictingTraits=new List<string>{"impatient_1","impatient_2","impatient_3"},
                requiredTraits=new List<string>{"patient_1"} },
            new PersonalityTrait { traitId="patient_3", traitName="坚忍", description="宽忍——之所以能比一切都更持久——无论是恩怨、争执，还是对手的寿命——仅仅是因为拒绝被催促",
                category=TraitCategory.Personality, learningMod=3f, diplomacyMod=3f, martialMod=-3f,
                conflictingTraits=new List<string>{"impatient_1","impatient_2","impatient_3"},
                requiredTraits=new List<string>{"patient_2"} },
            // ===== 不耐烦 impatient（L1不耐烦/毛躁 · L2急躁 · L3草率）=====
            new PersonalityTrait { traitId="impatient_1", traitName="不耐烦", description="毛躁——一股迫切的去行动、决断，或是在别人还没把话说完前就打断对方的冲动",
                category=TraitCategory.Personality, martialMod=1f, warfareMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"patient_1","patient_2","patient_3"} },
            new PersonalityTrait { traitId="impatient_2", traitName="急躁", description="毛躁——急躁推动着整个宫廷的节奏；臣属们学会了简明扼要地呈报问题",
                category=TraitCategory.Personality, martialMod=2f, warfareMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"patient_1","patient_2","patient_3"},
                requiredTraits=new List<string>{"impatient_1"} },
            new PersonalityTrait { traitId="impatient_3", traitName="草率", description="毛躁——无法忍受漫长的审议；御前会议头一轮反对还没说完，决断便已做出，事后犹豫已为时已晚",
                category=TraitCategory.Personality, martialMod=3f, warfareMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"patient_1","patient_2","patient_3"},
                requiredTraits=new List<string>{"impatient_2"} },
            // ===== 傲慢 arrogant（L1傲慢/自负 · L2狂妄 · L3目中无人）=====
            new PersonalityTrait { traitId="arrogant_1", traitName="傲慢", description="自负——对自身价值的高估，渗入到与各个层级的每一次互动中",
                category=TraitCategory.Personality, martialMod=1f, diplomacyMod=-1f, charmMod=-1f,
                conflictingTraits=new List<string>{"humble_1","humble_2","humble_3"} },
            new PersonalityTrait { traitId="arrogant_2", traitName="狂妄", description="自负——傲慢在每次觐见中都显露无遗；对地位较低者态度冷淡，对地位相当者通过言辞提醒安分守己",
                category=TraitCategory.Personality, martialMod=2f, diplomacyMod=-2f, charmMod=-2f,
                conflictingTraits=new List<string>{"humble_1","humble_2","humble_3"},
                requiredTraits=new List<string>{"arrogant_1"} },
            new PersonalityTrait { traitId="arrogant_3", traitName="目中无人", description="自负——将自己凌驾于所有人之上；就连宣誓效忠的领主也必须毕恭毕敬，任何轻慢之举绝不容忍",
                category=TraitCategory.Personality, martialMod=3f, diplomacyMod=-3f, charmMod=-3f,
                conflictingTraits=new List<string>{"humble_1","humble_2","humble_3"},
                requiredTraits=new List<string>{"arrogant_2"} },
            // ===== 谦卑 humble（L1谦卑/谦逊 · L2谦卑 · L3深藏若虚）=====
            new PersonalityTrait { traitId="humble_1", traitName="谦卑", description="谦逊——对赞誉与褒奖安之若素地推却，哪怕那是应得的",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f, learningMod=1f,
                conflictingTraits=new List<string>{"arrogant_1","arrogant_2","arrogant_3"} },
            new PersonalityTrait { traitId="humble_2", traitName="谦卑", description="谦逊——谦逊广受称道；请愿者面对的是一个不拘礼节的倾听者，胜利功劳全数归于旁人",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f, learningMod=2f,
                conflictingTraits=new List<string>{"arrogant_1","arrogant_2","arrogant_3"},
                requiredTraits=new List<string>{"humble_1"} },
            new PersonalityTrait { traitId="humble_3", traitName="深藏若虚", description="谦逊——无人能劝其接受荣耀；以其自身名义竖立的雕像至今蒙尘，编年史家只能在他人催促下动笔",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f, learningMod=3f,
                conflictingTraits=new List<string>{"arrogant_1","arrogant_2","arrogant_3"},
                requiredTraits=new List<string>{"humble_2"} },
            // ===== 疑心 paranoid（L1疑心/警觉 · L2多疑 · L3疑神疑鬼）=====
            new PersonalityTrait { traitId="paranoid_1", traitName="疑心", description="警觉——将世间视作仇敌环伺，每阵沉默都读作密谋",
                category=TraitCategory.Personality, intrigueMod=1f, learningMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"trusting_1","trusting_2","trusting_3"} },
            new PersonalityTrait { traitId="paranoid_2", traitName="多疑", description="警觉——疑心已经影响到城堡的日常运转；食物要先经人试尝，信件要读上两遍",
                category=TraitCategory.Personality, intrigueMod=2f, learningMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"trusting_1","trusting_2","trusting_3"},
                requiredTraits=new List<string>{"paranoid_1"} },
            new PersonalityTrait { traitId="paranoid_3", traitName="疑神疑鬼", description="警觉——在每一道阴影中都窥见阴谋；卫兵增至三倍，廷臣们不敢两两低语，最真诚的朋友也不再被信任",
                category=TraitCategory.Personality, intrigueMod=3f, learningMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"trusting_1","trusting_2","trusting_3"},
                requiredTraits=new List<string>{"paranoid_2"} },
            // ===== 相信度 trusting（L1相信度/坦诚 · L2轻信他人 · L3天真）=====
            new PersonalityTrait { traitId="trusting_1", traitName="相信度", description="坦诚——相信他人的善言与善意，即使证据本不该如此薄弱",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f, intrigueMod=-1f,
                conflictingTraits=new List<string>{"paranoid_1","paranoid_2","paranoid_3"} },
            new PersonalityTrait { traitId="trusting_2", traitName="轻信他人", description="坦诚——坦诚广为人知；顾问们被给予很大的自由，针对亲近伙伴的指控往往被挥手遗忘",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f, intrigueMod=-2f,
                conflictingTraits=new List<string>{"paranoid_1","paranoid_2","paranoid_3"},
                requiredTraits=new List<string>{"trusting_1"} },
            new PersonalityTrait { traitId="trusting_3", traitName="天真", description="坦诚——对他人的信任已经成了领地承受不起的弱点；廷臣们公然利用这一点，只有核心忠臣还在保护他",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f, intrigueMod=-3f,
                conflictingTraits=new List<string>{"paranoid_1","paranoid_2","paranoid_3"},
                requiredTraits=new List<string>{"trusting_2"} },
            // ===== 社交能力 gregarious（L1社交能力/善交际 · L2合群 · L3热情洋溢）=====
            new PersonalityTrait { traitId="gregarious_1", traitName="社交能力", description="善交际——对陪伴、交谈和热闹大厅里那份温暖的向往",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f, stewardshipMod=1f,
                conflictingTraits=new List<string>{"shy_1","shy_2","shy_3"} },
            new PersonalityTrait { traitId="gregarious_2", traitName="合群", description="善交际——热衷于待客，塑造了整个家庭的氛围；城堡里几乎总是宾客盈门",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f, stewardshipMod=2f,
                conflictingTraits=new List<string>{"shy_1","shy_2","shy_3"},
                requiredTraits=new List<string>{"gregarious_1"} },
            new PersonalityTrait { traitId="gregarious_3", traitName="热情洋溢", description="善交际——无法忍受空荡荡的大厅；这里总是盛宴不断，屋檐下总有来客，寂静对他来说像外语一样陌生",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f, stewardshipMod=3f,
                conflictingTraits=new List<string>{"shy_1","shy_2","shy_3"},
                requiredTraits=new List<string>{"gregarious_2"} },
            // ===== 羞涩 shy（L1羞涩/腼腆 · L2害羞 · L3孤僻）=====
            new PersonalityTrait { traitId="shy_1", traitName="羞涩", description="腼腆——对陌生人的注视和拥挤厅堂的压迫感到的不适",
                category=TraitCategory.Personality, learningMod=1f, intrigueMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"gregarious_1","gregarious_2","gregarious_3"} },
            new PersonalityTrait { traitId="shy_2", traitName="害羞", description="腼腆——缄默是宫廷里流传的评价；求见者会被委婉地指导如何接近他",
                category=TraitCategory.Personality, learningMod=2f, intrigueMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"gregarious_1","gregarious_2","gregarious_3"},
                requiredTraits=new List<string>{"shy_1"} },
            new PersonalityTrait { traitId="shy_3", traitName="孤僻", description="腼腆——可以完全避开人群，只要条件允许；书信代替了演讲，安静房间里一位访客便足以度过一天",
                category=TraitCategory.Personality, learningMod=3f, intrigueMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"gregarious_1","gregarious_2","gregarious_3"},
                requiredTraits=new List<string>{"shy_2"} },
            // ===== 报复欲 vengeful（L1报复欲/记仇 · L2有仇必报 · L3睚眦必报）=====
            new PersonalityTrait { traitId="vengeful_1", traitName="报复欲", description="记仇——对被冒犯记忆悠长，讨还公道的耐心更持久，不论其间相隔多少年",
                category=TraitCategory.Personality, intrigueMod=1f, martialMod=1f,
                conflictingTraits=new List<string>{"forgiving_1","forgiving_2","forgiving_3"} },
            new PersonalityTrait { traitId="vengeful_2", traitName="有仇必报", description="记仇——仇怨远近皆知；旧敌恐惧自己落入其掌握的一天，微小的怠慢时机一到也会得到回应",
                category=TraitCategory.Personality, intrigueMod=2f, martialMod=2f,
                conflictingTraits=new List<string>{"forgiving_1","forgiving_2","forgiving_3"},
                requiredTraits=new List<string>{"vengeful_1"} },
            new PersonalityTrait { traitId="vengeful_3", traitName="睚眦必报", description="记仇——将数十年前的侮辱都已讨还，据称保有一整本未了仇怨的账簿；伸手可及范围内没有仇敌能安生度日",
                category=TraitCategory.Personality, intrigueMod=3f, martialMod=3f,
                conflictingTraits=new List<string>{"forgiving_1","forgiving_2","forgiving_3"},
                requiredTraits=new List<string>{"vengeful_2"} },
            // ===== 宽容心 forgiving（L1宽容心/宽宥 · L2宽恕 · L3宽宏大量）=====
            new PersonalityTrait { traitId="forgiving_1", traitName="宽容心", description="宽宥——愿意放下怨怼，让昨日的过错留在昨日",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f,
                conflictingTraits=new List<string>{"vengeful_1","vengeful_2","vengeful_3"} },
            new PersonalityTrait { traitId="forgiving_2", traitName="宽恕", description="宽宥——宽大为怀是宫廷中有名一幕；请愿者来时旧已有罪却已被饶恕，一场叛乱都能以归还头衔结束",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f,
                conflictingTraits=new List<string>{"vengeful_1","vengeful_2","vengeful_3"},
                requiredTraits=new List<string>{"forgiving_1"} },
            new PersonalityTrait { traitId="forgiving_3", traitName="宽宏大量", description="宽宥——几乎本能地宽恕他人；即便是重大的背叛，也会以归还土地和一顿安静的饭食作为回应",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f,
                conflictingTraits=new List<string>{"vengeful_1","vengeful_2","vengeful_3"},
                requiredTraits=new List<string>{"forgiving_2"} },
            // ===== 色欲 lustful（L1色欲/轻媚 · L2好色 · L3荒淫）=====
            new PersonalityTrait { traitId="lustful_1", traitName="色欲", description="轻媚——对肉体欢愉的贪求，渗入每一次凝视与每一句挑逗之中",
                category=TraitCategory.Personality, diplomacyMod=1f, charmMod=1f,
                conflictingTraits=new List<string>{"chaste_1","chaste_2","chaste_3"} },
            new PersonalityTrait { traitId="lustful_2", traitName="好色", description="轻媚——好色之名传遍宫廷；情人的名单比臣属的名册还长，婚誓不过是一纸建议",
                category=TraitCategory.Personality, diplomacyMod=2f, charmMod=2f,
                conflictingTraits=new List<string>{"chaste_1","chaste_2","chaste_3"},
                requiredTraits=new List<string>{"lustful_1"} },
            new PersonalityTrait { traitId="lustful_3", traitName="荒淫", description="轻媚——已将床笫之事抬升到国策的高度；使节来朝先被引至内室，联姻的意义只剩洞房那一夜",
                category=TraitCategory.Personality, diplomacyMod=3f, charmMod=3f,
                conflictingTraits=new List<string>{"chaste_1","chaste_2","chaste_3"},
                requiredTraits=new List<string>{"lustful_2"} },
            // ===== 贞洁 chaste（L1贞洁/矜持 · L2守贞 · L3禁欲）=====
            new PersonalityTrait { traitId="chaste_1", traitName="贞洁", description="矜持——对肉体欲望的克制，以及对忠诚与纯洁之德的珍视",
                category=TraitCategory.Personality, learningMod=1f, diplomacyMod=1f,
                conflictingTraits=new List<string>{"lustful_1","lustful_2","lustful_3"} },
            new PersonalityTrait { traitId="chaste_2", traitName="守贞", description="矜持——守贞之名远近皆知；宫廷里不见暧昧的眼色，婚誓被视作不可触碰的圣约",
                category=TraitCategory.Personality, learningMod=2f, diplomacyMod=2f,
                conflictingTraits=new List<string>{"lustful_1","lustful_2","lustful_3"},
                requiredTraits=new List<string>{"chaste_1"} },
            new PersonalityTrait { traitId="chaste_3", traitName="禁欲", description="矜持——已将肉体视作灵魂的牢笼；宫廷里连夫妻间的温存都被视作堕落，独身成了唯一的圣洁",
                category=TraitCategory.Personality, learningMod=3f, diplomacyMod=3f,
                conflictingTraits=new List<string>{"lustful_1","lustful_2","lustful_3"},
                requiredTraits=new List<string>{"chaste_2"} },
            // ===== 贪吃 gluttonous（L1贪吃/饕客 · L2暴食 · L3无餍）=====
            new PersonalityTrait { traitId="gluttonous_1", traitName="贪吃", description="饕客——对美食与佳酿的过度热爱，餐桌成了一天中最重要的场合",
                category=TraitCategory.Personality, stewardshipMod=-1f, diplomacyMod=1f,
                conflictingTraits=new List<string>{"temperate_1","temperate_2","temperate_3"} },
            new PersonalityTrait { traitId="gluttonous_2", traitName="暴食", description="饕客——暴食是宫廷里的笑谈也是传奇；宴席从正午持续到深夜，国库的一半填进了厨房",
                category=TraitCategory.Personality, stewardshipMod=-2f, diplomacyMod=2f,
                conflictingTraits=new List<string>{"temperate_1","temperate_2","temperate_3"},
                requiredTraits=new List<string>{"gluttonous_1"} },
            new PersonalityTrait { traitId="gluttonous_3", traitName="无餍", description="饕客——已将吃升华为一种仪式；御厨比宰相更有权势，饥荒之年宫廷的宴席依旧如山",
                category=TraitCategory.Personality, stewardshipMod=-3f, diplomacyMod=3f,
                conflictingTraits=new List<string>{"temperate_1","temperate_2","temperate_3"},
                requiredTraits=new List<string>{"gluttonous_2"} },
            // ===== 节制 temperate（L1节制/有度 · L2克己 · L3绝嗜）=====
            new PersonalityTrait { traitId="temperate_1", traitName="节制", description="有度——对饮食与享乐的克制，凡事适可而止的生活态度",
                category=TraitCategory.Personality, stewardshipMod=1f, learningMod=1f,
                conflictingTraits=new List<string>{"gluttonous_1","gluttonous_2","gluttonous_3"} },
            new PersonalityTrait { traitId="temperate_2", traitName="克己", description="有度——克己是宫廷的典范；宴席上从不贪杯，饮食简单到让御厨觉得受了侮辱",
                category=TraitCategory.Personality, stewardshipMod=2f, learningMod=2f,
                conflictingTraits=new List<string>{"gluttonous_1","gluttonous_2","gluttonous_3"},
                requiredTraits=new List<string>{"temperate_1"} },
            new PersonalityTrait { traitId="temperate_3", traitName="绝嗜", description="有度——已将一切口腹之欲视作软弱；清水与粗面包是唯一的餐食，奢华的宴席令其作呕",
                category=TraitCategory.Personality, stewardshipMod=3f, learningMod=3f,
                conflictingTraits=new List<string>{"gluttonous_1","gluttonous_2","gluttonous_3"},
                requiredTraits=new List<string>{"temperate_2"} },
            // ===== 无常 arbitrary（L1无常/随性 · L2专断 · L3独裁专制）=====
            new PersonalityTrait { traitId="arbitrary_1", traitName="无常", description="随性——治事不循法度，唯凭一时喜怒；所下裁断亦随当日心境而屈伸",
                category=TraitCategory.Personality, intrigueMod=1f, diplomacyMod=-1f, stewardshipMod=-1f,
                conflictingTraits=new List<string>{"just_1","just_2","just_3"} },
            new PersonalityTrait { traitId="arbitrary_2", traitName="专断", description="随性——裁决是每日的赌局；请愿者得细究他们的情绪如同钻研法规，管家悄悄记录明日又可能被推翻的事项",
                category=TraitCategory.Personality, intrigueMod=2f, diplomacyMod=-2f, stewardshipMod=-2f,
                conflictingTraits=new List<string>{"just_1","just_2","just_3"},
                requiredTraits=new List<string>{"arbitrary_1"} },
            new PersonalityTrait { traitId="arbitrary_3", traitName="独裁专制", description="随性——治事全凭喜怒；昨日所赐赦免，明日或成绞索；廷中官吏无人敢信一纸令谕，除非墨迹已干过两回",
                category=TraitCategory.Personality, intrigueMod=3f, diplomacyMod=-3f, stewardshipMod=-3f,
                conflictingTraits=new List<string>{"just_1","just_2","just_3"},
                requiredTraits=new List<string>{"arbitrary_2"} },
            // ===== 公正 just（L1公正/公道 · L2正直 · L3大义凛然）=====
            new PersonalityTrait { traitId="just_1", traitName="公正", description="公道——对正义的坚持，无论出于法律还是良知，即使付出代价也不动摇",
                category=TraitCategory.Personality, diplomacyMod=1f, stewardshipMod=1f, learningMod=1f,
                conflictingTraits=new List<string>{"arbitrary_1","arbitrary_2","arbitrary_3"} },
            new PersonalityTrait { traitId="just_2", traitName="正直", description="公道——公正已成为其领地的一大特点；请愿者甚至从邻近的土地前来，编年史家记下了那些不利于领主亲族的裁决",
                category=TraitCategory.Personality, diplomacyMod=2f, stewardshipMod=2f, learningMod=2f,
                conflictingTraits=new List<string>{"arbitrary_1","arbitrary_2","arbitrary_3"},
                requiredTraits=new List<string>{"just_1"} },
            new PersonalityTrait { traitId="just_3", traitName="大义凛然", description="公道——建立起了跨越疆界的声誉；诸王会就公义之事向他请教，甚至连死敌也承认他裁断公平",
                category=TraitCategory.Personality, diplomacyMod=3f, stewardshipMod=3f, learningMod=3f,
                conflictingTraits=new List<string>{"arbitrary_1","arbitrary_2","arbitrary_3"},
                requiredTraits=new List<string>{"just_2"} },
            // ===== 施虐 sadistic（L1施虐/残忍 · L2虐待狂 · L3悖逆常伦）=====
            new PersonalityTrait { traitId="sadistic_1", traitName="施虐", description="残忍——一种从他人的痛苦中获得的快感，只要当天无事打扰便会主动去寻求",
                category=TraitCategory.Personality, intrigueMod=1f, martialMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"} },
            new PersonalityTrait { traitId="sadistic_2", traitName="虐待狂", description="残忍——残忍是众所周知的；仆人们在进入房间前都会做好心理准备，囚犯的命运被精心策划、乐在其中地安排",
                category=TraitCategory.Personality, intrigueMod=2f, martialMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"},
                requiredTraits=new List<string>{"sadistic_1"} },
            new PersonalityTrait { traitId="sadistic_3", traitName="悖逆常伦", description="残忍——纯粹从他人的痛苦中得到快乐；造访地牢乃是自愿，处刑的场面不止被容忍，更经其亲手布置",
                category=TraitCategory.Personality, intrigueMod=3f, martialMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"compassionate_1","compassionate_2","compassionate_3"},
                requiredTraits=new List<string>{"sadistic_2"} },
            // ===== 固执 stubborn（L1固执/坚决 · L2顽固 · L3冥顽不化）=====
            new PersonalityTrait { traitId="stubborn_1", traitName="固执", description="坚决——一旦采取立场便拒不退让，不论风向如何转变",
                category=TraitCategory.Personality, martialMod=1f, learningMod=1f, diplomacyMod=-1f,
                conflictingTraits=new List<string>{"fickle_1","fickle_2","fickle_3"} },
            new PersonalityTrait { traitId="stubborn_2", traitName="顽固", description="坚决——固执是御前会议的特点；幕僚们晓得定下的立场无法撼动，对手们也据此制定策略",
                category=TraitCategory.Personality, martialMod=2f, learningMod=2f, diplomacyMod=-2f,
                conflictingTraits=new List<string>{"fickle_1","fickle_2","fickle_3"},
                requiredTraits=new List<string>{"stubborn_1"} },
            new PersonalityTrait { traitId="stubborn_3", traitName="冥顽不化", description="坚决——不能被道理、证据或白纸黑字的错误所说动；整个领地会随他们一道坠下悬崖，在此之前绝不肯承认踏错了一步",
                category=TraitCategory.Personality, martialMod=3f, learningMod=3f, diplomacyMod=-3f,
                conflictingTraits=new List<string>{"fickle_1","fickle_2","fickle_3"},
                requiredTraits=new List<string>{"stubborn_2"} },
            // ===== 易变无定 fickle（L1易变无定/优柔寡断 · L2善变 · L3反复无常）=====
            new PersonalityTrait { traitId="fickle_1", traitName="易变无定", description="优柔寡断——偏好、忠诚和意图的摇摆不定，鲜少决定能维持过一周",
                category=TraitCategory.Personality, intrigueMod=1f, diplomacyMod=-1f, stewardshipMod=-1f,
                conflictingTraits=new List<string>{"stubborn_1","stubborn_2","stubborn_3"} },
            new PersonalityTrait { traitId="fickle_2", traitName="善变", description="优柔寡断——反复广受谈论；廷臣学会了绝不在确认今日旨意之前执行昨日的命令，条约的阅览也总瞄着下一次重谈",
                category=TraitCategory.Personality, intrigueMod=2f, diplomacyMod=-2f, stewardshipMod=-2f,
                conflictingTraits=new List<string>{"stubborn_1","stubborn_2","stubborn_3"},
                requiredTraits=new List<string>{"fickle_1"} },
            new PersonalityTrait { traitId="fickle_3", traitName="反复无常", description="优柔寡断——完全不受任何定见支配；宴席中途联盟便告瓦解，臣属的任免在同一个呼吸间颁布又收回",
                category=TraitCategory.Personality, intrigueMod=3f, diplomacyMod=-3f, stewardshipMod=-3f,
                conflictingTraits=new List<string>{"stubborn_1","stubborn_2","stubborn_3"},
                requiredTraits=new List<string>{"fickle_2"} },
            // ===== 怪癖 eccentric（L1怪癖/奇特 · L2古怪 · L3荒诞不经）=====
            new PersonalityTrait { traitId="eccentric_1", traitName="怪癖", description="奇特——在衣装、习俗和言谈上偏爱异乎寻常，使之有别于常礼",
                category=TraitCategory.Personality, learningMod=1f, intrigueMod=1f, diplomacyMod=-1f },
            new PersonalityTrait { traitId="eccentric_2", traitName="古怪", description="奇特——怪癖是宫廷中公开的特色；访客事先会得到警告，家宅也早已不再有非议",
                category=TraitCategory.Personality, learningMod=2f, intrigueMod=2f, diplomacyMod=-2f,
                requiredTraits=new List<string>{"eccentric_1"} },
            new PersonalityTrait { traitId="eccentric_3", traitName="荒诞不经", description="奇特——已全然偏离常俗；学者远道来研究他们，宫廷礼仪围绕着他们的习惯被重写，来访使节在归途上仍津津有味地复述他们的故事",
                category=TraitCategory.Personality, learningMod=3f, intrigueMod=3f, diplomacyMod=-3f,
                requiredTraits=new List<string>{"eccentric_2"} },
        };

        /// <summary>按 traitId 查找标签定义（无则 null）</summary>
        public static PersonalityTrait Get(string traitId)
        {
            foreach (var t in All)
                if (t.traitId == traitId) return t;
            return null;
        }

                /// <summary>获取某标签的升级目标（L1→L2，L2→L3；无升级返回 null）</summary>
        public static PersonalityTrait GetUpgrade(string traitId)
        {
            if (traitId.EndsWith("_1"))
                return Get(traitId.Replace("_1", "_2"));
            if (traitId.EndsWith("_2"))
                return Get(traitId.Replace("_2", "_3"));
            return null;
        }
    }
}
